//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makaleİslem
    {
        public int id { get; set; }
        public Nullable<int> makaleid { get; set; }
        public Nullable<int> baseditörid { get; set; }
        public Nullable<System.DateTime> baseditörislem { get; set; }
        public string alaneditorrapor { get; set; }
        public string baseditorcevap { get; set; }
        public Nullable<int> alaneditörid { get; set; }
        public Nullable<System.DateTime> alaneditörislem { get; set; }
        public Nullable<int> alaneditorcevap { get; set; }
        public Nullable<int> yazarid { get; set; }
        public Nullable<System.DateTime> yazarislem { get; set; }
        public Nullable<System.DateTime> hakemid1islem { get; set; }
        public Nullable<System.DateTime> hakemid2islem { get; set; }
        public Nullable<System.DateTime> hakemid3islem { get; set; }
        public Nullable<int> hakemid1 { get; set; }
        public Nullable<int> hakemid2 { get; set; }
        public Nullable<int> hakemid3 { get; set; }
        public Nullable<int> hakem1cevap { get; set; }
        public Nullable<int> hakem2cevap { get; set; }
        public Nullable<int> hakem3cevap { get; set; }
        public string hakem1rapor { get; set; }
        public string hakem2rapor { get; set; }
        public string hakem3rapor { get; set; }
        public Nullable<int> hakem1puan { get; set; }
        public Nullable<int> hakem2puan { get; set; }
        public Nullable<int> hakem3puan { get; set; }
        public string hakem1pdf { get; set; }
        public string hakem2pdf { get; set; }
        public string hakem3pdf { get; set; }
    }
}
