//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazar
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string mail { get; set; }
        public string tel { get; set; }
        public Nullable<int> sonislem { get; set; }
        public Nullable<int> aktif { get; set; }
        public Nullable<int> tur { get; set; }
        public Nullable<int> yasaklama { get; set; }
        public string parola { get; set; }
        public Nullable<System.DateTime> kayit { get; set; }
    }
}
