//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AljenFormProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakem
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string alan { get; set; }
        public Nullable<short> aktif { get; set; }
        public string yasaklama { get; set; }
        public Nullable<System.DateTime> sonislem { get; set; }
        public string parola { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
