//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AljenFormProject.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MakaleEntities : DbContext
    {
        public MakaleEntities()
            : base("name=MakaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Editör> Editör { get; set; }
        public virtual DbSet<Hakem> Hakem { get; set; }
        public virtual DbSet<Makale> Makale { get; set; }
        public virtual DbSet<Makaleİslem> Makaleİslem { get; set; }
        public virtual DbSet<Revizyon> Revizyon { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yazar> Yazar { get; set; }
    }
}
